server:
  port: 9294
spring:
  application:
    name: dataquery-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qxdatabase?useSSL=false
    username: root
    password: 123456
  data:
    redis:
      database: 15
      host: 81.71.161.47
      port: 6379
      password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka