server:
  port: 9194
spring:
  application:
    name: user-client-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/meteo_user?useSSL=false
    username: root
    password: 123456
  #    password: c209c209
  data:
    redis:
      database: 1
      host: organwalk.ink
      port: 6379
      password: z2113653402
      timeout: 5000
      jedis:
        pool:
          max-idle: 6
          max-active: 32
          max-wait: 100
          min-idle: 4

#      host: 192.168.1.132
#      port: 6379
#      password: c209c209
  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  security:
    user:
      password:
        encoder: bcrypt


