server:
  port: 9194
spring:
  application:
    name: user-client-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://organwalk.ink:33306/meteo_user?useSSL=false
    url: jdbc:mysql://localhost:3306/meteo_user?useSSL=false
    username: root
    password: c209c209
  data:
    redis:
      database: 1
#      host: organwalk.ink
#      port: 36379
      host: localhost
      port: 6379
      password: c209c209
  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  security:
    user:
      password:
        encoder: bcrypt


