server:
  port: 9094
spring:
  application:
    name: meteo-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: meteo-process-resource
          uri: lb://meteo-process-resource
          predicates:
            - Path=/qx/**
        - id: user-client-service
          uri: lb://user-client-service
          predicates:
            - Path=/user/**
    nacos:
      discovery:
        server-addr: localhost:8848
debug: true
