server:
  port: 9494
udp:
  remote:
    host: localhost
    port: 9092
spring:
  application:
    name: meteo-obtain-resource
  data:
    redis:
      database: 1
      host: 主机
      port: 端口
      password: 密码
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://主机:端口/meteo_data?useSSL=false
    username: 用户名
    password: 密码
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




