server:
  port: 9494
udp:
  remote:
    host: localhost
    port: 9092
spring:
  application:
    name: meteo-obtain-resource
  data:
    redis:
      database: 1
      host: 192.168.1.132
      port: 6379
      password: c209c209
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/meteo_data?useSSL=false
    username: root
    password: c209c209
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




