server:
  port: 9494
#udp:
#  remote:
#    host: 127.0.0.1
#    port: 9092
udp:
  remote:
    host: 81.71.161.47
    port: 39092
spring:
  application:
    name: meteo-obtain-resource
  rabbitmq:
    host: 81.71.161.47
    port: 35672
    username: guest
    password: guest
    listener:
      simple:
        message-converter: json
#  data:
#    redis:
#      database: 15
#      host: 81.71.161.47
#      port: 6379
#      password: 123456
  data:
    redis:
      database: 1
      host: 81.71.161.47
      port: 36379
      password: c209c209
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://81.71.161.47:33306/meteo_data?useSSL=false
    username: root
    password: c209c209
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


